// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotCua.Infrastructure.Data;

#nullable disable

namespace MotCua.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507071049_AddPhanHoi")]
    partial class AddPhanHoi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotCua.Domain.Entities.TinNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaGui")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuiLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoiGui")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SoLanThu")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("YeuCauId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YeuCauId");

                    b.HasIndex("DaGui", "TaoLuc");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("MotCua.Domain.Entities.YeuCauHoiDap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaYeuCau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TepDinhKem")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSinhVien");

                    b.HasIndex("MaYeuCau")
                        .IsUnique();

                    b.ToTable("YeuCauHoiDaps");
                });

            modelBuilder.Entity("MotCua.Domain.Entities.TinNhan", b =>
                {
                    b.HasOne("MotCua.Domain.Entities.YeuCauHoiDap", "YeuCau")
                        .WithMany("TinNhans")
                        .HasForeignKey("YeuCauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCau");
                });

            modelBuilder.Entity("MotCua.Domain.Entities.YeuCauHoiDap", b =>
                {
                    b.Navigation("TinNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
